### ISSUE TITLE
Excellent! But how to deal w/ empty cells?

### ISSUE THREAD

**Issue by johnpublish** [DLarsen/jquery-sumtr#1]
Since the calculation doesn't allow empty cells, how would you modify the script to act as if empty cells are zero, without actually rendering those values? 

Other than that, great plugin.

**Comment by DLarsen** [comment]
I just added an update to handle empty cells gracefully.

Quite often I pass in my own function to read the value.  See the example in the README, which is...

```
$('#myTable').sumtr({
    readValue : function(e) {
        /// do whatever you want here
        return parseFloat(e.data('val'));
    }
});
```

**Comment by johnpublish** [comment]
Splendid. Thanks for the update!
